### ISSUE TITLE
Sandbox options

### ISSUE THREAD

**Issue by laredson** [Angry362/Lifestyle-Mod-Project-Zomboid-#1]
Hello!

I'm happy to inaugurate the using of github for this project.

As far as I've used this site, we gather different aspects in the form of "issues" until you create a new section for development, sugestions, betatesting etc

First thing came to my mind while reading the description is the sandbox options. As we tried to balance during my patch lifetime, I came to the conclusion we must not only balance to our criteria but let the user choose their own if that's wanted.
This is the case of meditation, as is my main concern on this mod and my highest field of knowledge (asides as game designer)
Your rates are good, those are made to fit your playstyle. For example my playstyle differs (as many players do) there's so much ways to play this game and all of them are valuable experiences. Some will want to play a server for months IRL, maybe some others wanna make a 14 ingame-days event/challenge. And in between there's a lot too.

Summarizing:
You balance it the way you feel it must be played, there's your offering to the player. And then they'll be free to give it a try or modify.

This is why I think is very important a sandbox menu for the mod to reach even more people!

**Comment by Angry362** [comment]
Hey there!

Completely agree, sandbox options are a great idea to let people tailor the experience to their own tastes. Will definitely be adding them in the future.
