### ISSUE TITLE
Lifestyle experience multiplier does not affect by vanila sandbox settings

### ISSUE THREAD

**Issue by W1nKille3r** [Angry362/Lifestyle-Mod-Project-Zomboid-#11]
It clearly shouldn't work like that, I play with 2x multiplier where from level 0 to level 2 I have to reach very fast, lifestyle apparently ignores the value of vanilla settings. Also you can not change the experience multiplier in the settings of the mod itself.

It feels like the mod for singleplayer at all not tested and not looked at.

**Comment by W1nKille3r** [comment]
It's worth adding that getting +0.0X experience is a real mockery.

**Comment by W1nKille3r** [comment]
Just in case, I'll write down what I know about the difference in experience when the character is tired. The thing is that the character when he gets 39 experience at level 7. He should be getting 78.

**Comment by Angry362** [comment]
Hello, to increase xp gain for music you have to change the Music Strength value in sandbox options.
