### ISSUE TITLE
SUGGESTION: Dancing with True Music

### ISSUE THREAD

**Issue by jonathanjacobs** [Angry362/Lifestyle-Mod-Project-Zomboid-#3]
Sorry for posting here - I couldn't post in your Discord channel, which is where your wiki says to post suggestions. 

Here's our suggestion: Would it be possible to make the Dancing skill compatible with True Music Vol. 3 ? where you would gain skill points by dancing to music being played on turntables or cassette decks?

The players on our public server love this mod - but we also have tons of True Music installed as well, so making the Lifestyle framework compatible with True Music would be fantastic. :)

**Comment by Angry362** [comment]
Thanks for letting me know, I've made the discord server public only very recently and likely forgot to modify permissions.

As for the suggestions, not possible currently, but I'll see if there's a way to patch on my side.

**Comment by jonathanjacobs** [comment]
This is great! Hopefully it won't be too difficult to add.
