### ISSUE TITLE
Error on Level 3 Mindfulness Moodle w/Smoker Trait

### ISSUE THREAD

**Issue by AstroDogeDX** [Angry362/Lifestyle-Mod-Project-Zomboid-#4]
Hi,

I appear to be having a consistent issue when achieving Level 3 (Perfect Mindfulness) while also having the Smoker trait.

`function: updatePlayerTrackerByMinute -- file: PlayerTracker.lua line # 827 | MOD: Lifestyle`

Seems to have an issue with setting the TimeSinceLastSmoke to zero. Not sure what else in the log might be of use to, please let me know what you need and where to find it and I will provide!

Many thank yous for such an impressive mod nevertheless!

**Comment by Angry362** [comment]
Thank you! Looking into this issue now.

**Comment by Angry362** [comment]
Fix will be in the patch later today.

Issue was related to code incorrectly using getbodydamage instead of getstats for the setStressFromCigarettes. It now uses the correct method, tested and working.

Will close the issue, but please let me know should you need help in the future :)
