### ISSUE TITLE
General performance

### ISSUE THREAD

**Issue by Breakbeatss** [Angry362/Lifestyle-Mod-Project-Zomboid-#6]
2.Plethora of errors
3.on launch
4.~80 mods, must be a conflict
[console.txt](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/files/12738266/console.txt)

**Comment by Angry362** [comment]
Hey Breakbeatss, could not find an error coming from Lifestyle, but your logs show several errors coming from the following mods, your best bet is to talk with their authors:

Mod 1:
function: SpongieClothingZombiesZone.lua -- file: SpongieClothingZombiesZone.lua line # 15 | **MOD: Spongie's Clothing**

Mod 2:
function: DURGAM_ZombieZoneDefinition.lua -- file: DURGAM_ZombieZoneDefinition.lua line # 14 | **MOD: Danger Zone (State** of Emergency)

Mod 3:
function: handleUpdateAccZ -- file: AcceleratingZombies.lua line # 72 | **MOD: Secretmapper's Accelerating Zombies**
`Note: this last one is responsible for several error messages (function is likely trying to run each tick)`

**Comment by Breakbeatss** [comment]
thanks for lookin in m8!

**Comment by Angry362** [comment]
I'm glad I could help! Closing the issue now, but please let me know should you need help in the future :)
