### ISSUE TITLE
Issue with playing songs on server. 

### ISSUE THREAD

**Issue by Urgotopotamus** [Angry362/Lifestyle-Mod-Project-Zomboid-#8]
Having the issue where when trying to play music, the character instantly stops playing before they even start. Checked admin settings, checked quick worker as well, neither were causing an issue.  attached is a zip of all my logs.

[09-10-23_18-38-12_logs.zip](https://github.com/Angry362/Lifestyle-Mod-Project-Zomboid-/files/12851074/09-10-23_18-38-12_logs.zip)

**Comment by Angry362** [comment]
Hello, I'll need more information if you don't mind:

What instrument you were using; your music level; is it happening to all instruments; is it happening to other players; is the server using the any mod that reduces the time actions take to complete; when the character stops playing does the instrument make a "fail sound" or simply no sound; was the instant actions admin power enabled; are you able to play instruments in singleplayer or a local host with only Lifestyle enabled.

**Comment by Urgotopotamus** [comment]
I think I found out what happened, it was just zomboid being zomboid.  It
started working after quitting the game and loading back in. Not sure why
it randomly stopped but hey it’s working fine now!

**Comment by Angry362** [comment]
I'm glad to hear it! Let me know should you need any help in the future :)
